// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQQAvSyf9j6g4Jbnsfg2aZPtFGuAQLlRM',
    appId: '1:146023183986:web:1bd361fcc71cb847b1b4eb',
    messagingSenderId: '146023183986',
    projectId: 'fair-p-shop',
    authDomain: 'fair-p-shop.firebaseapp.com',
    storageBucket: 'fair-p-shop.firebasestorage.app',
    measurementId: 'G-W9HP2WJFX8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJRRh0ER3B_cS8-hMwKvicRPTKmUBEz2Y',
    appId: '1:182640675896:android:253a1d6d7164fc3d83aacd',
    messagingSenderId: '182640675896',
    projectId: 'fair-price-shop-6e85e',
    storageBucket: 'fair-price-shop-6e85e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvws4g5sd-fqZw80JNEieHcV30HDWf2Go',
    appId: '1:146023183986:ios:49c481896ec7648cb1b4eb',
    messagingSenderId: '146023183986',
    projectId: 'fair-p-shop',
    storageBucket: 'fair-p-shop.firebasestorage.app',
    iosBundleId: 'com.fairprice.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvws4g5sd-fqZw80JNEieHcV30HDWf2Go',
    appId: '1:146023183986:ios:49c481896ec7648cb1b4eb',
    messagingSenderId: '146023183986',
    projectId: 'fair-p-shop',
    storageBucket: 'fair-p-shop.firebasestorage.app',
    iosBundleId: 'com.fairprice.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQQAvSyf9j6g4Jbnsfg2aZPtFGuAQLlRM',
    appId: '1:146023183986:web:832f21c89965c437b1b4eb',
    messagingSenderId: '146023183986',
    projectId: 'fair-p-shop',
    authDomain: 'fair-p-shop.firebaseapp.com',
    storageBucket: 'fair-p-shop.firebasestorage.app',
    measurementId: 'G-SVXFZZEE6Q',
  );

}