import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:shared_preferences/shared_preferences.dart';

import 'providers/provider.dart';
import 'screens/login_screen.dart';
import 'screens/home_screen.dart';
import 'theme/palette.dart'; // <- keep palette

// Push + Firebase
import 'services/push_service.dart'; // exposes navServiceKey + init()
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // generated by FlutterFire

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // 1) Firebase first
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // 2) Initialize your runtime palette (do not remove)
  await PaletteManager.init();

  // 3) Init push (FCM + local notifications)
  await PushService.init();

  // 4) Start app
  runApp(
    ChangeNotifierProvider(create: (_) => CartProvider(), child: const MyApp()),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  Future<bool> _isLoggedIn() async {
    final prefs = await SharedPreferences.getInstance();
    final token = prefs.getString('token');
    return token != null && token.trim().isNotEmpty;
  }

  static Future<void> logout(BuildContext context) async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.remove('token');
    await prefs.remove('phone');
    await prefs.remove('user_id');

    if (context.mounted) {
      // Optional: PushService.unregisterDevice(authToken: '');
      Navigator.pushAndRemoveUntil(
        context,
        MaterialPageRoute(builder: (_) => const LoginScreen()),
        (route) => false,
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    return ValueListenableBuilder<AppPalette>(
      valueListenable: PaletteManager.instance,
      builder: (context, palette, _) {
        return MaterialApp(
          navigatorKey: navServiceKey, // <- from PushService for notif navigation
          title: 'Fair Price Shop',
          debugShowCheckedModeBanner: false,
          theme: ThemeData(
            useMaterial3: true,
            colorSchemeSeed: kPrimary, // <- palette color
            scaffoldBackgroundColor: kBgBottom, // <- palette color
            cardColor: kCard, // <- palette color
            fontFamily: 'Serif',

            appBarTheme: AppBarTheme(
              backgroundColor: kBgTop, // <- palette color
              foregroundColor: kTextPrimary, // <- palette color
              elevation: 0,
              iconTheme: IconThemeData(color: kTextPrimary),
              titleTextStyle: TextStyle(
                color: kTextPrimary,
                fontFamily: 'Serif',
                fontWeight: FontWeight.w700,
                fontSize: 20,
              ),
            ),

            bottomNavigationBarTheme: BottomNavigationBarThemeData(
              backgroundColor: Colors.white,
              selectedItemColor: kPrimary,
              unselectedItemColor: kTextPrimary.withOpacity(0.6),
              selectedLabelStyle: const TextStyle(fontFamily: 'Serif'),
              unselectedLabelStyle: const TextStyle(fontFamily: 'Serif'),
              showUnselectedLabels: true,
              type: BottomNavigationBarType.fixed,
            ),

            floatingActionButtonTheme: FloatingActionButtonThemeData(
              backgroundColor: kPrimary,
              foregroundColor: Colors.white,
            ),

            progressIndicatorTheme: ProgressIndicatorThemeData(color: kPrimary),

            snackBarTheme: SnackBarThemeData(
              backgroundColor: kPrimary,
              contentTextStyle: const TextStyle(color: Colors.white),
              actionTextColor: Colors.white,
              behavior: SnackBarBehavior.fixed,
            ),

            dividerTheme: DividerThemeData(color: kBorder),

            inputDecorationTheme: InputDecorationTheme(
              filled: true,
              fillColor: Colors.white,
              border: OutlineInputBorder(
                borderRadius: BorderRadius.circular(30),
                borderSide: BorderSide.none,
              ),
              contentPadding: const EdgeInsets.symmetric(
                horizontal: 20,
                vertical: 16,
              ),
            ),
          ),
          home: FutureBuilder<bool>(
            future: _isLoggedIn(),
            builder: (context, snap) {
              if (snap.connectionState == ConnectionState.waiting) {
                return const Scaffold(
                  body: Center(child: CircularProgressIndicator()),
                );
              }
              final loggedIn = snap.data == true;
              return loggedIn ? const HomePage() : const LoginScreen();
            },
          ),
        );
      },
    );
  }
}
